Now everything is sourceable

diff --git a/bin/websocket b/bin/websocket
--- a/bin/websocket
+++ b/bin/websocket
@@ -11,6 +11,7 @@ _last-seq(){
 }
 
 _dispatch-event(){
+
         #read -r PAYLOAD
         PAYLOAD="$1"
 
@@ -48,6 +49,7 @@ _dispatch-event(){
                 _last-seq | ws-send 1 "$SHARD"
 
                 sleep "$WAIT"
+		echo "$ACKF"
                 ACK=$(cat "$ACKF"); ACK="${ACK:-$LACK}"
                 [ "$LACK" -ge "$ACK" ] && (echo "null" | ws-send -1 "$SHARD")
                 echo "$(( ACK - LACK ))" > "$LATF"
@@ -82,6 +84,12 @@ _shard-loop(){
 }
 
 ws-start(){
+	if [ "$(set |(env;cat) | wc -c)" -ge 64000 ]; then
+		echo "Your environment is larger than 64kB, env_parallel can't work" >&2
+		echo "Don't source rest or long functions on the main script" >&2
+		exit 1
+	fi
+
 	[ "$MASH_AUTH_BOT" == "1" ] && SHARDS=$(echo " " | dapi GET "/gateway/bot" | jq -r '.shards//empty')
 	SHARDS="${SHARDS:-1}"
 	for ((I=0;I<$SHARDS;I++)); do
@@ -102,7 +110,7 @@ ewait(){
 	done < <(timeout "${2:-0}" tail -n0 -qf "$MASH_STATUS_DIR/ws_log_"* | jq -cM --stream --unbuffered "$QUERY") 
 }
 
-if [[ $_ == $0 ]]; then
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
 	echo "Usage: source websocket" >&2
 	echo "Websocket connection and functions"
 	echo ""
@@ -114,9 +122,14 @@ if [[ $_ == $0 ]]; then
 	echo "    using MASH_DISPATCH_{EVENT} environment variables"
 	echo ""
 	echo "ws-send {OP_CODE} [SHARD]"
-	echo "    Sends the JSON data from the STDIN to the gateway, default by SHARD 0"
+	echo "    Sends the JSON data from the STDIN to the gateway"
+	echo "        OP_CODE: The opcode for the operation" 
+	echo "        SHARD: The shard that will send it, default is 0"
 	echo ""
 	echo "ewait {CONDITION} [TIMEOUT]" >&2
-       	echo "    Watches the log until it finds a event that meet the jq condition, and outputs it"
+       	echo "    Watches the log until it finds a event that meet "
+	echo "    the jq condition, and outputs it"
+	echo "        CONDITION: A Jq string that returns a boolean"
+	echo "        TIMEOUT: In seconds, 0 for never expire"
 fi
 
